spring:
  main:
    web-application-type: SERVLET

app:
  server-base-url: "http://localhost:8081"

cert-base-path: "classpath:"

---
spring:
  config:
    activate:
      on-profile: "ssl"
  ssl:
    bundle:
      pem:
        web:
          keystore:
            certificate: "${cert-base-path}web-client-certs/tls.crt"
            private-key: "${cert-base-path}web-client-certs/tls.key"
          truststore:
            certificate: "${cert-base-path}web-client-certs/ca.crt"

app:
  server-base-url: "https://localhost:8443"
  ssl:
    bundle: "web"
