spring:
  main:
    web-application-type: SERVLET

app:
  server-base-url: "http://localhost:8081"

---
spring:
  config:
    activate:
      on-profile: "ssl"
  ssl:
    bundle:
      pem:
        web:
          keystore:
            certificate: "classpath:certs/web-client.crt"
            private-key: "classpath:certs/web-client.key"
          truststore:
            certificate: "classpath:certs/ca.crt"

app:
  server-base-url: "https://localhost:8443"
  ssl:
    bundle: "web"
