---
apiVersion: v1
kind: ConfigMap
metadata:
  name: books-server-config
data:
  application.yml: |
    spring:
      data:
        redis:
          host: "redis.default.svc.cluster.local"
    server:
      port: "8080"
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: books-server
  name: books-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-server
  strategy: {}
  template:
    metadata:
      labels:
        app: books-server
    spec:
      containers:
      - image: localhost:5001/books-server:0.0.1-SNAPSHOT
        name: books-server
        volumeMounts:
          - name: books-server-config
            mountPath: /workspace/config
            readOnly: true
        resources: {}
      volumes:
        - name: books-server-config
          configMap:
            name: books-server-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: books-server
  name: books-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: books-server
  type: ClusterIP
