---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  strategy: {}
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
        - image: docker.io/bitnami/redis:7.0
          name: redis
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 6379
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    service: redis
  ports:
    - name: "redis-client"
      port: 6379
      targetPort: 6379
